name: rngtr
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _pytorch_select=0.2=gpu_0
  - blas=1.0=mkl
  - ca-certificates=2020.7.22=0
  - certifi=2020.6.20=py37_0
  - cffi=1.13.2=py37h2e261b9_0
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.5=cuda10.0_0
  - freetype=2.9.1=h8a8886c_1
  - intel-openmp=2019.4=243
  - joblib=0.14.1=py_0
  - jpeg=9b=h024ee3a_2
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.9.0=py37hfd86e86_0
  - numpy=1.17.4=py37hc1035e2_0
  - numpy-base=1.17.4=py37hde5b4d6_0
  - olefile=0.46=py37_0
  - openssl=1.1.1g=h7b6447c_0
  - pillow=7.0.0=py37hb39fc2d_0
  - pip=19.3.1=py37_0
  - pycparser=2.19=py37_0
  - python=3.7.6=h0371630_2
  - pytorch=1.4.0=py3.7_cuda10.0.130_cudnn7.6.3_0
  - readline=7.0=h7b6447c_5
  - regex=2019.12.9=py37h7b6447c_0
  - scikit-learn=0.22.1=py37hd81dba3_0
  - setuptools=44.0.0=py37_0
  - six=1.13.0=py37_0
  - sqlite=3.30.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - torchvision=0.5.0=py37_cu100
  - tqdm=4.41.1=py_0
  - wheel=0.33.6=py37_0
  - xz=5.2.4=h14c3975_4
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - absl-py==0.9.0
    - alabaster==0.7.12
    - allennlp==1.1.0
    - allennlp-models==1.1.0
    - astor==0.8.1
    - astunparse==1.6.3
    - attrs==19.3.0
    - babel==2.8.0
    - backcall==0.1.0
    - bleach==3.1.1
    - blis==0.2.4
    - boto3==1.14.60
    - botocore==1.17.60
    - cachetools==4.0.0
    - chardet==3.0.4
    - click==7.0
    - conllu==4.1
    - cycler==0.10.0
    - cymem==2.0.3
    - cython==0.29.16
    - decorator==4.4.2
    - defusedxml==0.6.0
    - dill==0.3.1.1
    - docutils==0.15.2
    - editdistance==0.5.3
    - entrypoints==0.3
    - fairseq==0.9.0
    - filelock==3.0.12
    - flaky==3.6.1
    - flask==1.1.1
    - flask-cors==3.0.8
    - ftfy==5.6
    - future==0.18.2
    - gast==0.3.3
    - gevent==1.4.0
    - google-auth==1.11.2
    - google-auth-oauthlib==0.4.1
    - google-pasta==0.1.8
    - greenlet==0.4.15
    - grpcio==1.27.2
    - h5py==2.10.0
    - idna==2.8
    - imagesize==1.2.0
    - importlib-metadata==1.4.0
    - ipykernel==5.1.4
    - ipython==7.13.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - itsdangerous==1.1.0
    - jedi==0.16.0
    - jinja2==2.10.3
    - jmespath==0.9.4
    - jsonlines==1.2.0
    - jsonnet==0.14.0
    - jsonpickle==1.2
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.0.0
    - jupyter-console==6.1.0
    - jupyter-core==4.6.3
    - keras==2.4.3
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - kiwisolver==1.1.0
    - markdown==3.2.1
    - markupsafe==1.1.1
    - matplotlib==3.1.2
    - mecab-python3==0.996.5
    - mistune==0.8.4
    - more-itertools==8.1.0
    - murmurhash==1.0.2
    - nbconvert==5.6.1
    - nbformat==5.0.4
    - nltk==3.4.5
    - notebook==6.0.3
    - numpydoc==0.9.2
    - oauthlib==3.1.0
    - opt-einsum==3.1.0
    - overrides==3.1.0
    - packaging==20.0
    - pandocfilters==1.4.2
    - parsimonious==0.8.1
    - parso==0.6.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - plac==0.9.6
    - pluggy==0.13.1
    - portalocker==1.6.0
    - preshed==2.0.1
    - prometheus-client==0.7.1
    - prompt-toolkit==3.0.4
    - protobuf==3.11.2
    - ptyprocess==0.6.0
    - py==1.8.1
    - py-rouge==1.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyconll==2.2.1
    - pygments==2.5.2
    - pyparsing==2.4.6
    - pyrsistent==0.15.7
    - pytest==5.3.4
    - python-dateutil==2.8.1
    - pytorch-pretrained-bert==0.6.2
    - pytorch-transformers==1.1.0
    - pytz==2019.3
    - pyyaml==5.3.1
    - pyzmq==19.0.0
    - qtconsole==4.7.1
    - qtpy==1.9.0
    - requests==2.22.0
    - requests-oauthlib==1.3.0
    - responses==0.10.9
    - rsa==4.0
    - s3transfer==0.3.0
    - sacrebleu==1.4.6
    - sacremoses==0.0.38
    - scipy==1.4.1
    - send2trash==1.5.0
    - sentencepiece==0.1.85
    - snowballstemmer==2.0.0
    - spacy==2.1.9
    - sphinx==2.3.1
    - sphinxcontrib-applehelp==1.0.1
    - sphinxcontrib-devhelp==1.0.1
    - sphinxcontrib-htmlhelp==1.0.2
    - sphinxcontrib-jsmath==1.0.1
    - sphinxcontrib-qthelp==1.0.2
    - sphinxcontrib-serializinghtml==1.1.3
    - sqlparse==0.3.0
    - srsly==1.0.1
    - tabulate==0.8.7
    - tensorboardx==2.1
    - termcolor==1.1.0
    - terminado==0.8.3
    - testpath==0.4.4
    - thinc==7.0.8
    - tokenizers==0.0.11
    - torchtext==0.2.1
    - tornado==6.0.4
    - traitlets==4.3.3
    - transformers==2.4.1
    - typing==3.7.4.1
    - unidecode==1.1.1
    - urllib3==1.25.7
    - wasabi==0.6.0
    - wcwidth==0.1.8
    - webencodings==0.5.1
    - werkzeug==0.16.0
    - widgetsnbextension==3.5.1
    - word2number==1.1
    - wrapt==1.12.0
    - zipp==2.0.0
